---
- hosts: nodes
  become: yes
  tasks:
          - name: install a apache server
            yum: name=apache2 state=present
            notify: restart apache
  handlers:
          - name: restart apache
            service: name=apache2 state=restarted
            

